#' @name  a_coxph_hr
#' @title a_coxph_hr
#' @description a_coxph_hr `r lifecycle::badge("deprecated")` Use
#'   tern:::a_coxph_pairwise()` instead, and use `tern::coxph_pairwise()` as
#'   the layout-level wrapper.
#' @inheritParams odds_ratio
#' @export
a_coxph_hr <- function(
    df,
    .var,
    ref_path,
    .spl_context,
    ...,
    .stats = NULL,
    .formats = NULL,
    .labels = NULL,
    .indent_mods = NULL) {
  lifecycle::deprecate_stop(
    when = "0.1.7",
    what = "a_coxph_hr()",
    with = "tern:::a_coxph_pairwise()",
    details = "Use `tern:::coxph_pairwise()` as the layout-level wrapper."
  )
}

#' @name  s_coxph_hr
#' @title s_coxph_hr
#' @description s_coxph_hr `r lifecycle::badge("deprecated")` Use
#'  `tern::s_coxph_pairwise`  instead, and use `tern::coxph_pairwise()` as
#'   the layout-level wrapper.
#' @inheritParams odds_ratio
#' @keywords internal
s_coxph_hr <- function(
    df,
    .var,
    ref_path,
    .spl_context,
    ...,
    .stats = NULL,
    .formats = NULL,
    .labels = NULL,
    .indent_mods = NULL) {
  lifecycle::deprecate_stop(
    when = "0.1.7",
    what = "s_coxph_hr()",
    with = "tern:::s_coxph_pairwise()",
    details = "Use `tern:::coxph_pairwise()` as the layout-level wrapper."
  )
}

#' @title s_kaplan_meier
#' @description `r lifecycle::badge("deprecated")` Use [tern::s_surv_time()] instead.
#' @keywords internal
s_kaplan_meier <- function(df, .var, is_event, control = control_surv_time()) {
  lifecycle::deprecate_stop(
    when = "0.1.7",
    what = "s_kaplan_meier()",
    with = "tern::s_surv_time()",
    details = paste0(
      "Note: the label for `range_with_cens_info` has changed from ",
      "'Min, max' (junco) to 'Min - Max (with censoring)' (tern)."
    )
  )
}

#' @title rbmi_ancova
#' @description `r lifecycle::badge("deprecated")` Use [rbmi::ancova()] instead.
#' @param data (`data.frame`) input data.
#' @param vars (`list`) vars object from `rbmi::set_vars()`.
#' @param visits (`character`) optional visit filter.
#' @param weights (`character`) weighting strategy.
#' @export
rbmi_ancova <- function(
  data,
  vars,
  visits = NULL,
  weights = c("counterfactual", "equal", "proportional_em", "proportional")
) {
  lifecycle::deprecate_stop(
    when = "0.1.7",
    what = "rbmi_ancova()",
    with = "rbmi::ancova()"
  )
}

#' @title a_kaplan_meier
#' @description `r lifecycle::badge("deprecated")` Use [tern::a_surv_time()] instead.
#' @param df (`data.frame`) input data.
#' @param .var (`string`) variable name.
#' @param ... additional arguments (ignored).
#' @param .stats (`character`) statistics to compute (ignored).
#' @param .formats (`list`) formats for statistics (ignored).
#' @param .labels (`list`) labels for statistics (ignored).
#' @param .indent_mods (`list`) indentation modifications (ignored).
#' @export
a_kaplan_meier <- function(df, .var, ..., .stats = NULL, .formats = NULL, .labels = NULL, .indent_mods = NULL) {
  lifecycle::deprecate_stop(
    when = "0.1.7",
    what = "a_kaplan_meier()",
    with = "tern::a_surv_time()",
    details = paste0(
      "Note: the label for `range_with_cens_info` has changed from ",
      "'Min, max' (junco) to 'Min - Max (with censoring)' (tern)."
    )
  )
}

#' Parallelise Lapply
#'
#' @description
#' `r lifecycle::badge("deprecated")` This internal helper is no longer exported.
#' Use `rbmi::analyse()` directly.
#'
#' @param cl (`cluster object`)\cr Cluster created by [`parallel::makeCluster()`] or `NULL`
#' @param fun (`functions`)\cr Function to be run
#' @param x (`object`)\cr Object to be looped over
#' @param ... Extra arguments passed to `fun`
#' @return `list` of results of calling `fun` on elements of `x`.
par_lapply <- function(cl, fun, x, ...) {
  lifecycle::deprecate_stop(
    when = "0.1.6",
    what = "par_lapply()",
    details = "Use `rbmi::analyse()` directly."
  )
}

#' Analyse Multiple Imputed Datasets
#'
#' @description
#' This function takes multiple imputed datasets (as generated by
#' the impute() function from the rbmi package) and runs an analysis function on
#' each of them.
#'
#'
#' @details
#' This function works by performing the following steps:
#'
#' 1. Extract a dataset from the `imputations` object.
#' 2. Apply any delta adjustments as specified by the `delta` argument.
#' 3. Run the analysis function `fun` on the dataset.
#' 4. Repeat steps 1-3 across all of the datasets inside the `imputations`
#' object.
#' 5. Collect and return all of the analysis results.
#'
#' The analysis function `fun` must take a `data.frame` as its first
#' argument. All other options to [rbmi_analyse()] are passed onto `fun`
#'
#' @param imputations An `imputations` object as created by the impute() function from the rbmi package.
#' @param fun An analysis function to be applied to each imputed dataset. See details.
#' @param delta A `data.frame` containing the delta transformation to be applied to the imputed
#' datasets prior to running `fun`. See details.
#' @param ... Additional arguments passed onto `fun`.
#' @param cluster_or_cores (`numeric` or `cluster object`)\cr
#' The number of parallel processes to use when running this function. Can also be a
#' cluster object created by [`make_rbmi_cluster()`]. See the parallelisation section below.
#' @param .validate (`logical`)\cr
#' Should `imputations` be checked to ensure it conforms to the required format
#' (default = `TRUE`) ? Can gain a small performance increase if this is set to `FALSE` when
#' analysing a large number of samples.
#' @return An `analysis` object, as defined by `rbmi`, representing the desired
#' analysis applied to each of the imputed datasets in `imputations`.
#' @description
#' `r lifecycle::badge("deprecated")` Use `rbmi::analyse()` instead.
#'
#' @export
rbmi_analyse <- function(
  imputations,
  fun = rbmi_ancova,
  delta = NULL,
  ...,
  cluster_or_cores = 1,
  .validate = TRUE
) {
  lifecycle::deprecate_stop(
    when = "0.1.6",
    what = "rbmi_analyse()",
    with = "rbmi::analyse()"
  )
}
