#' Create a `rbmi` ready cluster
#'
#' @description
#' `r lifecycle::badge("deprecated")` Use `rbmi::make_rbmi_cluster()` instead.
#'
#' @param cluster_or_cores (`integer` or `cluster object`)\cr
#' Number of parallel processes to use or an existing cluster to make use of
#' @param objects (`list`)\cr A named list of objects to export into the sub-processes
#' @param packages (`character vector`)\cr
#' A character vector of libraries to load in the sub-processes
#'
#' @return See `rbmi::make_rbmi_cluster()`.
#' @export
make_rbmi_cluster <- function(
  cluster_or_cores = 1,
  objects = NULL,
  packages = NULL
) {
  lifecycle::deprecate_stop(
    when = "0.1.6",
    what = "make_rbmi_cluster()",
    with = "rbmi::make_rbmi_cluster()"
  )
} 

#' Parallelise Lapply
#'
#' @description
#' `r lifecycle::badge("deprecated")` This internal helper is no longer exported.
#' Use `rbmi::analyse()` directly.
#'
#' @param cl (`cluster object`)\cr Cluster created by [`parallel::makeCluster()`] or `NULL`
#' @param fun (`functions`)\cr Function to be run
#' @param x (`object`)\cr Object to be looped over
#' @param ... Extra arguments passed to `fun`
#' @return `list` of results of calling `fun` on elements of `x`.
par_lapply <- function(cl, fun, x, ...) {
  lifecycle::deprecate_stop(
    when = "0.1.6",
    what = "par_lapply()",
    details = "Use `rbmi::analyse()` directly."
  )
}

#' Analyse Multiple Imputed Datasets
#'
#' @description
#' This function takes multiple imputed datasets (as generated by
#' the impute() function from the rbmi package) and runs an analysis function on
#' each of them.
#'
#'
#' @details
#' This function works by performing the following steps:
#'
#' 1. Extract a dataset from the `imputations` object.
#' 2. Apply any delta adjustments as specified by the `delta` argument.
#' 3. Run the analysis function `fun` on the dataset.
#' 4. Repeat steps 1-3 across all of the datasets inside the `imputations`
#' object.
#' 5. Collect and return all of the analysis results.
#'
#' The analysis function `fun` must take a `data.frame` as its first
#' argument. All other options to [rbmi_analyse()] are passed onto `fun`
#'
#' @param imputations An `imputations` object as created by the impute() function from the rbmi package.
#' @param fun An analysis function to be applied to each imputed dataset. See details.
#' @param delta A `data.frame` containing the delta transformation to be applied to the imputed
#' datasets prior to running `fun`. See details.
#' @param ... Additional arguments passed onto `fun`.
#' @param cluster_or_cores (`numeric` or `cluster object`)\cr
#' The number of parallel processes to use when running this function. Can also be a
#' cluster object created by [`make_rbmi_cluster()`]. See the parallelisation section below.
#' @param .validate (`logical`)\cr
#' Should `imputations` be checked to ensure it conforms to the required format
#' (default = `TRUE`) ? Can gain a small performance increase if this is set to `FALSE` when
#' analysing a large number of samples.
#' @return An `analysis` object, as defined by `rbmi`, representing the desired
#' analysis applied to each of the imputed datasets in `imputations`.
#' @description
#' `r lifecycle::badge("deprecated")` Use `rbmi::analyse()` instead.
#'
#' @export
rbmi_analyse <- function(
  imputations,
  fun = rbmi_ancova,
  delta = NULL,
  ...,
  cluster_or_cores = 1,
  .validate = TRUE
) {
  lifecycle::deprecate_stop(
    when = "0.1.6",
    what = "rbmi_analyse()",
    with = "rbmi::analyse()"
  )
}
