name: Hotfix Tests

on:
  push:
    branches:
      - 'feature/hotfix-*'
  pull_request:
    branches: [main, CRAN]
  workflow_dispatch:

jobs:
  test-hotfix:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: '4.5.0'}
          - {os: ubuntu-latest,   r: '4.5.0'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools
            any::testthat

      - name: Execute tests with hotfixes
        shell: Rscript {0}
        run: |
          # 1. Load local junco source
          devtools::load_all(".")
          
          # 2. Inject Hotfix
          if (file.exists("dev/hotfix.R")) {
            message(">>> Injecting dev/hotfix.R")
            source("dev/junco_hotfix.R")
          } else {
            stop("Required hotfix file 'dev/junco_hotfix.R' is missing.")
          }
          
          # 3. Run tests in the current environment
          options(testthat.progress.max_reports = 10)
          results <- testthat::test_local(reporter = "progress")
          
          # 4. Exit with error code if any tests failed
          if (!testthat:::all_passed(results)) {
            stop("Tests failed with the current hotfix applied.")
          }