---
name: release 🕰️

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches: [main, CRAN]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      chosen-workflow:
        description: |
          Select which workflow you'd like to run
        required: true
        type: choice
        default: rhub
        options:
          - rhub
          - revdepcheck
          - hotfix

jobs:
  revdepcheck:
    if: >
      github.event_name == 'release' || (
        github.event_name == 'workflow_dispatch' &&
        inputs.chosen-workflow == 'revdepcheck'
      )
    name: revdepcheck 🧑‍🔬
    uses: johnsonandjohnson/junco/.github/workflows/revdepcheck.yaml@scda_test_reversedependency
  rhub:
    if: >
      github.event_name == 'release' || (
        github.event_name == 'workflow_dispatch' &&
        inputs.chosen-workflow == 'rhub'
      )
    name: R-hub 🌐
    uses: johnsonandjohnson/junco/.github/workflows/rhub.yaml@scda_test_reversedependency
  hotfix:
    if: >
      github.event_name == 'release' || (
        github.event_name == 'workflow_dispatch' &&
        inputs.chosen-workflow == 'hotfix'
      )
    name: hotfix-hub 🔥
    uses: johnsonandjohnson/junco/.github/workflows/hotfix.yaml@scda_test_reversedependency
