---
name: release 🕰️

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches: [main, CRAN]
  workflow_call:
    secrets:
      REPO_GITHUB_TOKEN:
        description: |
          Github token with read access to repositories
        required: false
  push:
    branches:
      - 'feature/hotfix-*'
  workflow_dispatch:
    inputs:
      chosen-workflow:
        description: |
          Select which workflow you'd like to run
        required: true
        type: choice
        default: rhub
        options:
          - rhub
          - revdepcheck
          - hotfix_v0-1-1
          - hotfix_v0-1-3
          - hotfix_v0-1-3-Eze

jobs:
  revdepcheck:
    name: revdepcheck 🧑‍🔬
    uses: johnsonandjohnson/actions/.github/workflows/revdepcheck.yaml@dev
  rhub:
    name: R-hub 🌐
    uses: johnsonandjohnson/actions/.github/workflows/rhub.yaml@dev
  hotfix_v0-1-1:
    name: hotfix v0.1.1🔥
    uses: johnsonandjohnson/actions/.github/workflows/hotfix_v0-1-1.yaml@dev
  hotfix_v0-1-3:
    name: hotfix v0.1.3🔥
    uses: johnsonandjohnson/actions/.github/workflows/hotfix_v0-1-3.yaml@dev
  hotfix_v0-1-3-Eze:
    name: hotfix v0.1.3-Eze🔥
    uses: johnsonandjohnson/actions/.github/workflows/hotfix_v0-1-3-Eze.yaml@dev
