---
name: Revdep 🧑‍🔬

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  revdepcheck:
    name: revdepcheck ↩️
    uses: insightsengineering/r.pkg.template/.github/workflows/revdepcheck.yaml@main