name: coverage-report

on:
  push:
    branches: [main, ci_cd]
  pull_request:
    branches: [main, ci_cd]

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to push to gh-pages

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "covr", "xml2"))
          remotes::install_deps(dependencies = TRUE)

      - name: Run test coverage
        run: |
          dir.create("coverage", showWarnings = FALSE)
          cov <- covr::package_coverage(type = "tests")
          covr::to_cobertura(cov, "coverage/cobertura.xml")
          covr::report(cov, file = "coverage/coverage.html")

          # Extract percentage
          percent <- round(covr::percent_coverage(cov))
          color <- if (percent > 90) "brightgreen" else if (percent > 75) "orange" else "red"
          url <- sprintf("https://img.shields.io/badge/coverage-%s%%25-%s.svg", percent, color)
          download.file(url, "coverage/badge.svg", quiet = TRUE)

      - name: Upload to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          publish_branch: gh-pages
          destination_dir: _xml_coverage_reports/data/main
