name: coverage-report

on:
  push:
    branches: [main, ci_cd]
  pull_request:
    branches: [main, ci_cd]

jobs:
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install covr
        run: Rscript -e 'install.packages("covr", repos = "https://cloud.r-project.org")'

      - name: Build & install your package
        run: |
          R CMD build .
          R CMD INSTALL junco_*.tar.gz

      - name: Run coverage and generate badge
        run: |
          mkdir -p coverage
          Rscript -e '
            cov <- covr::package_coverage(type = "tests")
            covr::to_cobertura(cov, "coverage/cobertura.xml")
            covr::report(cov, file = "coverage/coverage.html")
            pct <- round(covr::percent_coverage(cov))
            col <- if (pct >= 90) "brightgreen" else if (pct >= 75) "orange" else "red"
            url <- sprintf("https://img.shields.io/badge/coverage-%s%%25-%s.svg", pct, col)
            download.file(url, "coverage/badge.svg", quiet = TRUE)
          '

      - name: Deploy badge and reports to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          publish_branch: gh-pages
          destination_dir: _xml_coverage_reports/data/main
